import { useNavigation } from "@react-navigation/native";
import { Text, View } from "react-native";
import { TextButton } from "../components/Buttons";
import { H1, P } from "../components/Fonts";
import Spacer from "../components/Spacer";
import Screens from "../constants/screens";
import { acceptDisclaimer } from "../utils/disclaimerStorage";

const DisclaimerScreen = () => {
    const navigation = useNavigation<any>();

    const handleDisclaimerAcceptance = () => {
        acceptDisclaimer();
        navigation.replace(Screens.CAMERA)
    }

    return <View style={{ flex: 1, alignItems: 'center' }}>
        <Spacer height={120} />
        <H1>DeepTest</H1>
        <Spacer height={48} />

        <View style={{ width: "80%" }}>
            <P style={{ textAlign: "justify" }}><Text style={{ fontWeight: 'bold' }}>Disclaimer: </Text>
                This app is intended for research
                and informational purposes only. Output of app
                does not constitute medical advice. Information
                provided is not a substitute for professional
                medical advice, diagnosis or treatment. Always
                seek the advice of your physician or another
                qualified health provider. If you think you may
                have a medical emergency, call your doctor or
                emergency services immediately. All data
                generated by the app is stored locally and is
                destroyed when the app is removed.</P>
            <Spacer height={24} />
            <P style={{ textAlign: "justify" }}>
                Kindly continue to use the app only if you
                perfectly understand the implications of usage. This will not be
                shown again.</P>
            <Spacer height={36} />
            <View style={{ alignItems: "center" }}>
                <TextButton capitalise onPress={handleDisclaimerAcceptance}>I Understand</TextButton>
            </View>
        </View>
    </View>
}

export default DisclaimerScreen;